# ===========================
# DATABASE (PostgreSQL)
# ===========================
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-solitary-recipe-adk8ug0r-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_rznb1U9ZQqho}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# JPA / Hibernate
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===========================
# JWT
# ===========================
jwt.secret=${JWT_SECRET:oGR7qjzSo5y/xo4qMxN99GnafiiVsrjwkxvmY2WPzXSxb2DCV7pwO9VqMKfzM6XJ86eukYSA033eTZPQ==}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# ===========================
# Email (Gmail SMTP)
# ===========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:referal310u@gmail.com}
spring.mail.password=${MAIL_PASSWORD:bqjcmywbjguezote}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===========================
# Cloudinary
# ===========================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dr91el9gb}
cloudinary.api-key=${CLOUDINARY_API_KEY:159599643821244}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:5ul1xdqolzIGf_RbREf3VFneIAI}

# ===========================
# App
# ===========================
app.base-url=${APP_BASE_URL:http://localhost:5173}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB